[package]
name = "zinit"
version = "0.1.0"
authors = ["Muhamad Azmy <muhamad.azmy@codescalers.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.8"
futures = "0.1"
tokio = "0.1"
failure = "0.1"
shlex = "0.1"
clap = "2.33"
tokio-signal = "0.2"
nix = "0.14"
bitflags = "1.0.4"
log = "0.4"
simple_logger = "1.2.0"
rand = "0.7.2"
